version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Paris"
    ignore:
      - dependency-name: "expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "expo-web-browser"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest-expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native-reanimated"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Paris"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Paris"
